### ISSUE TITLE
JAWS does not narrate progressbar name with virtual cursor

### ISSUE THREAD

**Issue by adamsamec** [FreedomScientific/VFO-standards-support#650]
### Summary

JAWS does not narrate the accessible name of an element with the "progressbar" role when focused with the virtual cursor.

Steps to reproduce:

1. Visit [this demo page][example].
2. Using the virtual cursor, navigate to  every progressbar element each located under the example &lt;h2&gt; headings.
3. Using the Tab key, navigate to the focusable progressbar element located under the 'Example 3: With tabindex="0" and named using the "aria-label" attribute without element content' &lt;h2&gt; heading.

### Expected result

IN all the examples, perhaps except the first 1, when the virtual cursor moves on the given progressbar element, JAWS should narrate the accessible name of the progressbar, that is, in this case, "Updating...", followed by the string "Progress bar Indeterminate".

Especially the example 5 is a pattern which authors would likely use, so the progressbar label narration should be ensured in this case.

### Actual result

IN all the examples,  when the virtual cursor moves on the given progressbar element, JAWS narrates only "0 Progress bar Indeterminate", that is, it does not narrate the accessible name of the progressbar. However, if moved using the Tab key on a focusable progressbar, as instructed in the point 3 of the repro steps above, the accessible name is read correctly, although even in this case the narration is not perfect, since JAWS should not read "0" as the percentage of the progressbar because it is indeterminate.

### Example

[Test case that demonstrates the issue][example].

#### JAWS version and build number

JAWS Professional 2022.2206.9.
 
#### Operating System and version

Windows 11, version 21H2 (OS Build 22000.795)

#### Browser and version:

Google Chrome, version 103.0.5060.114

[example]: https://jsbin.com/dininiraxa/edit?html,output

**Comment by JAWS-test** [comment]
Example 1 cannot work because a progressbar does not allow to be labeled with its text content

**Comment by adamsamec** [comment]
I have modified the issue and provided more examples when the accessible name should definitely be read when focused with the virtual cursor. Please, could you review those changes and examples?

**Comment by JAWS-test** [comment]
I can confirm that the label is not output acoustically. However, it is displayed on the Braille display. This is a JAWS bug.

By the way, I do not hear "Indeterminate", but "partially activated". This may be a bug related to the language of my JAWS version (I don't use the English version).

**Comment by adamsamec** [comment]
Hello @JAWS-test ,

the narration of the indeterminate progressbar role has been fixed in JAWS 2022.2206. Before the update, JAWS announced the progressbar as "half checked" as you noted.

**Comment by JAWS-test** [comment]
The problem that the label is not output acoustically also occurs with the HTML element `<progress>`. Here, too, the maximum and minimum values are not acoustically perceptible.

**Comment by adamsamec** [comment]
Yes, apart from the &lt;progress&gt; HTML 5 element, the problem of not reading the element's label can be reproduced also on determinate progressbars, that is, on an element with the "progressbar" role having the "aria-voluenow" attribute set, and also on a &lt;progress&gt; HTML 5 element having the "value" attribute set.

**Comment by defalt18** [comment]
Using JAWS 2023

Jaws is not narrating the accessible name for progress bar (div with `role="progressbar"`) in the below scenario when focus lands on container div:

```html
<div class="container">
  <span>label</span>
  <div class="progress-container">
     <div role="progressbar"></div>
  </div>
  <!-- .... -->
</div>
``` 

I tried giving the container and progress container element `aria-live=assertive/polite` but it still does not acknowledge the progress bar presence.
